[linux_nodes]
node1 ansible_host=192.168.112.136
node2 ansible_host=192.168.112.141

[linux_nodes:vars]
ansible_python_interpreter=/usr/bin/python3
deploy_user=appuser
wordpress_port=8081
# 初始连接使用 root 账户进行环境初始化
ansible_user=root
